### ISSUE TITLE
Support for .NET 4.7 Framework

### ISSUE THREAD

**Issue by punitganshani** [Microsoft/BotBuilder-PersonalityChat#14]
The current Nuget package `Microsoft.Bot.Builder.PersonalityChat` has dependency on `.NET Standard, Version=v2.0` and BotBuilder supports both `ASPNET Core` and standard `ASP.NET` built on `.NET 4.7`

Do we have any plans to release a `.NET 4.7` framework compatible Nuget package?

**Comment by parag11** [comment]
For now, you can use the Microsoft.Bot.Builder.PersonalityChat.Core directly in your bot. Check sample in Csharp/core directory. You will have to write a few extra lines if you want to use it as a middlewares though

**Comment by parag11** [comment]
Let us know if that doesn't work for you.
